# Generated by Django 4.2.7 on 2026-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', '日报'), ('WEEKLY', '周报'), ('MONTHLY', '月报')], max_length=20)),
                ('report_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', '待生成'), ('GENERATING', '生成中'), ('COMPLETED', '已完成'), ('FAILED', '生成失败')], default='PENDING', max_length=20)),
                ('health_score', models.FloatField(default=0.0, help_text='健康评分(0-100)')),
                ('heart_rate_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('step_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('sleep_summary', models.JSONField(blank=True, default=dict, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '健康报告',
                'verbose_name_plural': '健康报告',
                'db_table': 'health_reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
