# Generated by Django 4.2.7 on 2026-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('SMART_BAND', '智能手环'), ('SMART_WATCH', '智能手表'), ('HEART_RATE_MONITOR', '心率监测仪'), ('SLEEP_TRACKER', '睡眠追踪器')], default='SMART_BAND', max_length=50)),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_level', models.IntegerField(default=100, help_text='电量百分比')),
                ('status', models.CharField(choices=[('ACTIVE', '激活'), ('INACTIVE', '未激活'), ('PAIRED', '已配对'), ('UNPAIRED', '未配对')], default='INACTIVE', max_length=20)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
            },
        ),
    ]
