const mongoose = require('mongoose');

const whiteboardSnapshotSchema = new mongoose.Schema({
  roomId: {
    type: String,
    required: true,
    index: true
  },
  name: {
    type: String,
    required: true,
    trim: true
  },
  elements: [{
    id: String,
    type: String,
    left: Number,
    top: Number,
    width: Number,
    height: Number,
    fill: String,
    stroke: String,
    strokeWidth: Number,
    angle: Number,
    scaleX: Number,
    scaleY: Number,
    opacity: Number,
    visible: Boolean,
    selectable: Boolean,
    evented: Boolean,
    lockMovementX: Boolean,
    lockMovementY: Boolean,
    lockRotation: Boolean,
    lockScalingX: Boolean,
    lockScalingY: Boolean,
    hasControls: Boolean,
    hasBorders: Boolean,
    text: String,
    fontSize: Number,
    fontFamily: String,
    fontWeight: String,
    fontStyle: String,
    underline: Boolean,
    linethrough: Boolean,
    textAlign: String,
    lineHeight: Number,
    charSpacing: Number,
    path: [[Number]],
    points: [{ x: Number, y: Number }],
    radius: Number,
    rx: Number,
    ry: Number,
    x1: Number,
    y1: Number,
    x2: Number,
    y2: Number,
    corners: [Number],
    src: String,
    crossOrigin: String,
    filters: [Object],
    shadow: Object,
    clipPath: Object,
    backgroundColor: String,
    originX: String,
    originY: String,
    skewX: Number,
    skewY: Number,
    flipX: Boolean,
    flipY: Boolean,
    perPixelTargetFind: Boolean,
    globalCompositeOperation: String,
    paintFirst: String,
    strokeDashArray: [Number],
    strokeDashOffset: Number,
    strokeLineCap: String,
    strokeLineJoin: String,
    strokeMiterLimit: Number,
    strokeUniform: Boolean,
    borderColor: String,
    borderDashArray: [Number],
    borderOpacityWhenMoving: Number,
    borderScaleFactor: Number,
    centeredScaling: Boolean,
    centeredRotation: Boolean,
    cornerColor: String,
    cornerDashArray: [Number],
    cornerSize: Number,
    cornerStrokeColor: String,
    cornerStyle: String,
    dirty: Boolean,
    excludeFromExport: Boolean,
    hoverCursor: String,
    includeDefaultValues: Boolean,
    inverted: Boolean,
    minScaleLimit: Number,
    moveCursor: String,
    noScaleCache: Boolean,
    objectCaching: Boolean,
    rotatingPointOffset: Number,
    selectionBackgroundColor: String,
    selectionColor: String,
    selectionDashArray: [Number],
    selectionLineWidth: Number,
    stateProperties: [String],
    type: String,
    version: String
  }],
  createdBy: {
    type: String,
    required: true
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  }
});

whiteboardSnapshotSchema.index({ roomId: 1, createdAt: -1 });

module.exports = mongoose.model('WhiteboardSnapshot', whiteboardSnapshotSchema);
