# Generated by Django 4.2.7 on 2026-05-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heart_rate', models.IntegerField(help_text='心率(次/分钟)')),
                ('confidence', models.FloatField(default=1.0, help_text='数据置信度(0-1)')),
            ],
            options={
                'verbose_name': '心率数据',
                'verbose_name_plural': '心率数据',
                'db_table': 'heart_rate_data',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('AWAKE', '清醒'), ('LIGHT', '浅睡'), ('DEEP', '深睡'), ('REM', 'REM')], default='LIGHT', max_length=20)),
                ('duration', models.IntegerField(help_text='持续时间(分钟)')),
                ('respiratory_rate', models.FloatField(blank=True, help_text='呼吸频率(次/分钟)', null=True)),
            ],
            options={
                'verbose_name': '睡眠数据',
                'verbose_name_plural': '睡眠数据',
                'db_table': 'sleep_data',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('steps', models.IntegerField(help_text='步数')),
                ('distance', models.FloatField(default=0.0, help_text='距离(米)')),
                ('calories', models.FloatField(default=0.0, help_text='消耗卡路里(千卡)')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='devices.device')),
            ],
            options={
                'verbose_name': '步数数据',
                'verbose_name_plural': '步数数据',
                'db_table': 'step_data',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
