# Generated by Django 4.2.7 on 2026-05-03 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='devices.device'),
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartratedata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='devices.device'),
        ),
        migrations.AddField(
            model_name='heartratedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
