# Generated by Django 4.2.7 on 2026-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('STEPS', '步数目标'), ('CALORIES', '卡路里目标'), ('DISTANCE', '距离目标'), ('SLEEP', '睡眠目标'), ('HEART_RATE', '心率目标')], max_length=30)),
                ('target_value', models.FloatField(help_text='目标值')),
                ('current_value', models.FloatField(default=0.0, help_text='当前值')),
                ('unit', models.CharField(help_text='单位', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '健康目标',
                'verbose_name_plural': '健康目标',
                'db_table': 'health_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GOAL_ACHIEVED', '目标达成'), ('REMINDER', '提醒通知'), ('HEALTH_ALERT', '健康警报'), ('DEVICE_ALERT', '设备提醒'), ('SYSTEM', '系统通知')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('SEDENTARY', '久坐提醒'), ('WATER', '饮水提醒'), ('MEDICATION', '服药提醒'), ('EXERCISE', '运动提醒'), ('SLEEP', '睡眠提醒'), ('CUSTOM', '自定义提醒')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_time', models.TimeField(help_text='提醒时间')),
                ('repeat', models.CharField(choices=[('ONCE', '一次'), ('DAILY', '每天'), ('WEEKLY', '每周'), ('WEEKDAYS', '工作日'), ('WEEKENDS', '周末')], default='DAILY', max_length=20)),
                ('active_days', models.JSONField(default=list, help_text='活动日期列表，如[1,2,3,4,5]表示周一至周五')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
                'db_table': 'reminders',
                'ordering': ['reminder_time'],
            },
        ),
    ]
